### ISSUE TITLE
Add link to GitHub on docs website

### ISSUE THREAD

**Issue by jwflory** [vrapeutic/vrapeutic.github.io#5]
There are several helpful links in the header and footer of the website, but I could not quickly find a way to get to the VRapeutic GitHub repositories from the docs site. Since this is a huge plus and it is something people will want to see, it is definitely worth making sure your GitHub is present on the website. 😀

**Comment by YahyaAlaaMassoud** [comment]
@all-contributors add @jwflory for ideas and review
